# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploymenttask',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='deploy_on',
            field=models.CharField(default='status', max_length=60),
        ),
        migrations.AlterField(
            model_name='deploymenttask',
            name='task_type',
            field=models.CharField(choices=[('SSH', 'SSH'), ('GIT_SSH', 'Git over SSH')], max_length=30),
        ),
    ]
