# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160505_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deploymenttask',
            name='task_type',
            field=models.CharField(choices=[('SSH', 'SSH'), ('GIT_SSH', 'Git over SSH'), ('EMAIL_NOTIFICATION', 'Email notification'), ('SLACK_NOTIFICATION', 'Slack notification')], max_length=30),
        ),
    ]
