# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deployment_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskresult',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='task_type',
            field=models.CharField(choices=[('SSH', 'SSH'), ('GIT_SSH', 'Git over SSH')], max_length=30),
        ),
    ]
