# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_auto_20160505_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='task_type',
            field=models.CharField(choices=[('SSH', 'SSH'), ('GIT_SSH', 'Git over SSH'), ('EMAIL_NOTIFICATION', 'Email notification'), ('SLACK_NOTIFICATION', 'Slack notification')], max_length=30),
        ),
    ]
